---
title: "pcr"
output: pdf_document
---

### 3. PCR (Iris)

```{r PCA_description}
set.seed(2)
# Need help with PCA analysis
# pcr.fit=pcr(SalePrice~., data=HousePricing, scale=TRUE, validation ="CV")
setwd("~/OneDrive - Worcester Polytechnic Institute (wpi.edu)/2020Fall/DS502/DS502FinalProject")
train.original = read.csv("./SourceData/train_original.csv")
train_ori = train.original
library(dplyr)
library(tidyr)
library(pls)

# PCA portion
train = sample(dim(train_ori)[1],size = dim(train_ori)[1]*0.7)
train.subset = train_ori[train,]
test = train_ori[-train,]
# bootstrap again
train.bs = sample(dim(train.subset)[1],replace = T)
train.df = train.subset[train.bs,]


# define a function to generate scree plots
pcaCharts <- function(x) {
  x.var <- x$sdev ^ 2
  x.pvar <- x.var/sum(x.var)
  print("proportions of variance:")
  print(x.pvar)
  
  par(mfrow=c(2,2))
  plot(x.pvar,xlab="Principal component", ylab="Proportion of variance explained", ylim=c(0,1), type='b',cex.lab=1, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)
  plot(cumsum(x.pvar),xlab="Principal component", ylab="Cumulative Proportion of variance explained", ylim=c(0,1), type='b',cex.lab=0.9, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)
  screeplot(x,cex.lab=0.8, cex.axis=0.8, cex.main=0.8, cex.sub=0.8)
  screeplot(x,type="l",cex.lab=0.8, cex.axis=0.8, cex.main=0.8, cex.sub=0.8)
  par(mfrow=c(1,1))
}

# x = subset(train.df, select = -c(SalePrice) )
# train.pca <- prcomp(x ,center = TRUE)
# pcaCharts(train.pca)

########################### insert an image  (pca_plot.png) #################################

# validationplot(pcr_fit, val.type = "MSEP",cex.lab=1, cex.axis=0.8, cex.main=1.5, cex.sub=0.8)
# axis(side = 1, at = c(32), cex.axis=0.8)
# abline(v = 32, col = "blue", lty = 5)
# abline(v = 26, col = "dark green", lty = 5)
# axis(side = 1, at = c(26), cex.axis=0.8)


########################### insert another image  (pcr_mse.png) #################################
```

```{r pcr_original}
# start pcr

pcr_fit = pcr(SalePrice~., data = train.df,validation = "CV")
pcr_pred = predict(pcr_fit,test)

accuracy.ori = mean((test$SalePrice - pcr_pred[,,32])/test$SalePrice<=0.2 & (test$SalePrice - pcr_pred[,,32])/test$SalePrice>=-0.05)


rsq <- function(x, y) summary(lm(y~x))$r.squared
rsq.ori = rsq(test$SalePrice,pcr_pred[,,32])

rmse <-  function(m, o){sqrt(mean((m - o)^2))}
rmse.ori = rmse(test$SalePrice,pcr_pred[,,32])


```

``` {r pcr_log}
setwd("~/OneDrive - Worcester Polytechnic Institute (wpi.edu)/2020Fall/DS502/DS502FinalProject")
train.log = read.csv("./SourceData/train_log.csv")
train_log = train.log
set.seed(667)
train = sample(dim(train_log)[1],size = dim(train_log)[1]*0.7)
train.subset = train_log[train,]
test = train_log[-train,]
# bootstrap again
train.bs = sample(dim(train.subset)[1],replace = T)
train.df = train.subset[train.bs,]
pcr_fit = pcr(SalePrice~., data = train.df,validation = "CV")
pcr_pred = predict(pcr_fit,test)
accuracy.log = mean((exp(test$SalePrice) - exp(pcr_pred[,,32]))/exp(test$SalePrice<=0.2) & (exp(test$SalePrice) - exp(pcr_pred[,,32]))/exp(test$SalePrice)>=-0.05)

rsq.log = rsq(test$SalePrice,pcr_pred[,,32])
rmse.log = rmse(exp(test$SalePrice),exp(pcr_pred[,,32]))

```

``` {r pcr_sqrt}
setwd("~/OneDrive - Worcester Polytechnic Institute (wpi.edu)/2020Fall/DS502/DS502FinalProject")
train.sqrt = read.csv("./SourceData/train_sqrt.csv")
train_sqrt = train.sqrt

set.seed(233)
train = sample(dim(train_sqrt)[1],size = dim(train_sqrt)[1]*0.7)
train.subset = train_sqrt[train,]
test = train_sqrt[-train,]
# bootstrap again
train.bs = sample(dim(train.subset)[1],replace = T)
train.df = train.subset[train.bs,]
pcr_fit = pcr(SalePrice~., data = train.df,validation = "CV")
pcr_pred = predict(pcr_fit,test)
accuracy.sqrt = mean((test$SalePrice^4 - pcr_pred[,,32]^4)/test$SalePrice^4<=0.2 & (test$SalePrice^4 - pcr_pred[,,32]^4)/test$SalePrice^4>=-0.05)

rsq.sqrt = rsq(test$SalePrice,pcr_pred[,,32])
rmse.sqrt = rmse(test$SalePrice^4,pcr_pred[,,32]^4)
```

#### Cross Validation

``` {r pcr_cv}
x <- data.frame("y" = c("original","log","sqrt"), "Accuracy" = c(accuracy.ori,accuracy.log,accuracy.sqrt), "R2" = c(rsq.ori,rsq.log,rsq.sqrt),"RMSE" = c(rmse.ori,rmse.log,rmse.sqrt))
pander(x)

```
